### ISSUE TITLE
Issue, Self-hosted Thin Backend

### ISSUE THREAD

**Issue by wzalazar** [digitallyinduced/thin-backend#64]
Hi guys, I followed the tutorial on https://thin.dev/docs/self-hosting

I copied and pasted

```
services:
  db:
    image: postgres:alpine3.16
    restart: always
    environment:
      POSTGRES_PASSWORD: examplepassword
    ports:
      - '5432:5432'
  thin:
    image: downloads.digitallyinduced.com/digitallyinduced/thin-backend:latest
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:examplepassword@db/postgres"
      TYPE_DEFINITONS_BASE_PATH: "$PWD"
    volumes:
      - ".:/home/app/Application:rw"
```

and after that I run `docker-compose up`

I'm getting this issue 

<img width="1157" alt="Screen Shot 2022-10-01 at 16 20 14" src="https://user-images.githubusercontent.com/5795257/193425007-aeec9a59-4022-4bfa-9884-56b8daba3664.png">

thanks in advance, nice project!

PD: there is a typo here in the documentation

<img width="695" alt="Screen Shot 2022-10-01 at 16 21 55" src="https://user-images.githubusercontent.com/5795257/193425052-a74ea68a-3f50-4dc7-bb5c-539fcde87fe3.png">
